Allow iterable dataset for detector fit
TorchDrift/TorchDrift pull request #16
Opened 2022-07-11 13:37 UTC by alessiamarcolini

Fixes #15

2022-08-24 21:10 UTC, lantiga requested changes
Thank you @alessiamarcolini! 
Looks great, only a minor nit

2022-08-24 21:10 UTC, lantiga commented on torchdrift/utils/fit.py
> +        if num_batches and i >= num_batches:
```suggestion
        if num_batches is not None and i >= num_batches:
```

2022-08-24 22:10 UTC, lantiga approved these changes

2022-08-25 20:43 UTC, alessiamarcolini commented
Hi @lantiga, I don't think the failures are related to my changes :D

2022-08-25 20:54 UTC, t-vi commented
Looks awesome, thank you @alessiamarcolini .

2022-08-26 08:15 UTC, merged